#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and saying "hi" on the 9th line
i=1

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
