#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and saying "bad luck" on the 4th line and "good luck" on the 8th line
i=1

while [ $i -le 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "good luck"
	elif [ $i -eq 4 ]
		then
		       echo "bad luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
