#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and saying "bad luck" on the 4th line and "good luck" on the 8th line
i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i+1))
done
