#!/usr/bin/env bash
# This script gives you infromation about a file

file=school

if [ -e $file ]
then
	echo "$file file exists"
	if [ -s $file ]
	then
		echo "$file file is empty"
	else
		echo "$file file is not empty"
		if [ -f $file ]
		then
			echo "$file is a regular file"
		fi
	fi
else
	echo "$file file does not exist"
fi
