#!/usr/bin/env bash
# A script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
# ignore shellcheck suggestion for pgrep

ps -auxf | grep "bash"
